services:
  app:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - api
    networks:
      - api-net

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/toDo-db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - db
    networks:
      - db-net
      - api-net

  db:
    image: "postgres:alpine"
    #ports:
    #  - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=toDo-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-net

volumes:
  pgdata: {}

networks:
  db-net:
  api-net:
