version: '3.7'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: to-do-app
    ports:
      - 5433:5432
    depends_on:
      - db
  db:
    image: 'postgres:15.3-alpine3.18'
    container_name: db
    network_mode: host
    environment:
      - POSTGRES_DB=todoappdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin