services:
  app:
    build:
      context: ./frontend
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - api-net

  api:
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-net
      - api-net

  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db-net

volumes:
  pgdata: {}

networks:
  api-net:
  db-net:
    external: true