version: '3.9'

services:
  app:
    container_name: todoapp
    image: mchalet/todoapp:1.0.0
    build: .
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/todoappdbp
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - db
  db:
    image: 'postgres:12'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todoappdbp
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}